FROM ubuntu:22.04

# TODO remove sudo for user "magma" to avoid unwanted priv escalation from
# other attack vectors.

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y sudo make build-essential git wget tree vim gdb zstd libzstd-dev libjbig-dev libselinux-dev linux-tools-common linux-tools-generic linux-cloud-tools-generic

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

# RUN echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main" >> /etc/apt/sources.list
# RUN echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main" >> /etc/apt/sources.list
# RUN echo "# 11" >> /etc/apt/sources.list
# RUN echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" >> /etc/apt/sources.list
# RUN echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y clang-14 llvm-14-dev libc++-14-dev libc++abi-14-dev \
    gcc-11-plugin-dev libssl-dev cargo autopoint python3-dev lld-14

RUN update-alternatives \
  --install /usr/lib/llvm              llvm             /usr/lib/llvm-14  20 \
  --slave   /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-14  \
    --slave   /usr/bin/llvm-ar           llvm-ar          /usr/bin/llvm-ar-14 \
    --slave   /usr/bin/llvm-as           llvm-as          /usr/bin/llvm-as-14 \
    --slave   /usr/bin/llvm-bcanalyzer   llvm-bcanalyzer  /usr/bin/llvm-bcanalyzer-14 \
    --slave   /usr/bin/llvm-c-test       llvm-c-test      /usr/bin/llvm-c-test-14 \
    --slave   /usr/bin/llvm-cov          llvm-cov         /usr/bin/llvm-cov-14 \
    --slave   /usr/bin/llvm-diff         llvm-diff        /usr/bin/llvm-diff-14 \
    --slave   /usr/bin/llvm-dis          llvm-dis         /usr/bin/llvm-dis-14 \
    --slave   /usr/bin/llvm-dwarfdump    llvm-dwarfdump   /usr/bin/llvm-dwarfdump-14 \
    --slave   /usr/bin/llvm-extract      llvm-extract     /usr/bin/llvm-extract-14 \
    --slave   /usr/bin/llvm-link         llvm-link        /usr/bin/llvm-link-14 \
    --slave   /usr/bin/llvm-mc           llvm-mc          /usr/bin/llvm-mc-14 \
    --slave   /usr/bin/llvm-nm           llvm-nm          /usr/bin/llvm-nm-14 \
    --slave   /usr/bin/llvm-objdump      llvm-objdump     /usr/bin/llvm-objdump-14 \
    --slave   /usr/bin/llvm-ranlib       llvm-ranlib      /usr/bin/llvm-ranlib-14 \
    --slave   /usr/bin/llvm-readobj      llvm-readobj     /usr/bin/llvm-readobj-14 \
    --slave   /usr/bin/llvm-rtdyld       llvm-rtdyld      /usr/bin/llvm-rtdyld-14 \
    --slave   /usr/bin/llvm-size         llvm-size        /usr/bin/llvm-size-14 \
    --slave   /usr/bin/llvm-stress       llvm-stress      /usr/bin/llvm-stress-14 \
    --slave   /usr/bin/llvm-symbolizer   llvm-symbolizer  /usr/bin/llvm-symbolizer-14 \
    --slave   /usr/bin/llvm-tblgen       llvm-tblgen      /usr/bin/llvm-tblgen-14

RUN update-alternatives \
  --install /usr/bin/clang                 clang                  /usr/bin/clang-14     20 \
  --slave   /usr/bin/clang++               clang++                /usr/bin/clang++-14 \
  --slave   /usr/bin/clang-cpp             clang-cpp              /usr/bin/clang-cpp-14

RUN clang --version

## Magma directory hierarchy
# magma_root is relative to the docker-build's working directory
# The Docker image must be built in the root of the magma directory
ARG magma_root=./

## Path variables inside the container
ENV MAGMA_R=/magma
ENV OUT=/magma_out
ENV SHARED=/magma_shared

ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
ENV LD=/usr/bin/ld
ENV AR=/usr/bin/ar
ENV AS=/usr/bin/as
ENV NM=/usr/bin/nm
ENV RANLIB=/usr/bin/ranlib

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN mkdir -p /home && \
	groupadd -g 1000 magma && \
	useradd -l -u 1000 -K UMASK=0000 -d /home -g magma magma && \
	chown magma:magma /home
RUN	echo "magma:amgam" | chpasswd && usermod -a -G sudo magma

RUN mkdir -p ${SHARED} ${OUT} && \
	chown magma:magma ${SHARED} ${OUT} && \
	chmod 777 ${SHARED} ${OUT}

ARG magma_path=magma
ENV MAGMA=${MAGMA_R}/${magma_path}
USER root:root
RUN mkdir -p ${MAGMA} && chown magma:magma ${MAGMA}
COPY --chown=magma:magma ${magma_root}/${magma_path} ${MAGMA}/
RUN ${MAGMA}/preinstall.sh
USER magma:magma
RUN ${MAGMA}/prebuild.sh

ARG fuzzer_name
ARG fuzzer_path=fuzzers/${fuzzer_name}
ENV FUZZER=${MAGMA_R}/${fuzzer_path}
USER root:root
RUN mkdir -p ${FUZZER} && chown magma:magma ${FUZZER}
COPY --chown=magma:magma ${magma_root}/${fuzzer_path} ${FUZZER}/
# RUN ${FUZZER}/preinstall.sh
USER magma:magma
RUN ${FUZZER}/fetch.sh
RUN ${FUZZER}/build.sh

ARG target_name
ARG target_path=targets/${target_name}
ENV TARGET=${MAGMA_R}/${target_path}
USER root:root
RUN mkdir -p ${TARGET} && chown magma:magma ${TARGET}
COPY --chown=magma:magma ${magma_root}/${target_path} ${TARGET}/
RUN ${TARGET}/preinstall.sh
USER magma:magma
RUN ${TARGET}/fetch.sh
RUN ${MAGMA}/apply_patches.sh

## Configuration parameters
ARG isan
ARG harden
ARG canaries
ARG fixes

ARG ISAN_FLAG=${isan:+-DMAGMA_FATAL_CANARIES}
ARG HARDEN_FLAG=${harden:+-DMAGMA_HARDEN_CANARIES}
ARG CANARIES_FLAG=${canaries:+-DMAGMA_ENABLE_CANARIES}
ARG FIXES_FLAG=${fixes:+-DMAGMA_ENABLE_FIXES}
ARG BUILD_FLAGS="-include ${MAGMA}/src/canary.h ${CANARIES_FLAG} ${FIXES_FLAG} ${ISAN_FLAG} ${HARDEN_FLAG} -g -O0"

ENV CFLAGS=${BUILD_FLAGS}
ENV CXXFLAGS=${BUILD_FLAGS}
# CYHADDED: 多加两个动态库 -ljbig -lzstd
ENV LIBS="-l:magma.o -lrt -ljbig -lzstd"
ENV LDFLAGS="-L${OUT} -g"

RUN ${FUZZER}/instrument.sh

# RUN chmod 777 ${MAGMA}/filter_corpus.sh 
# RUN ${MAGMA}/filter_corpus.sh

ENTRYPOINT "${MAGMA}/run.sh"





